version: 0.2

env:
  variables:
    REGION: ap-south-1
    ACCOUNT_ID: 948082844272
    SOHAM_IMAGE: soham-app-app
    ZAID_IMAGE: zaid-app-app

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

  build:
    commands:
      - echo Building Docker images...
      - docker build -t $SOHAM_IMAGE ./soham-app
      - docker build -t $ZAID_IMAGE ./zaid-app

      - echo Tagging images...
      - docker tag $SOHAM_IMAGE:latest $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$SOHAM_IMAGE:latest
      - docker tag $ZAID_IMAGE:latest $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ZAID_IMAGE:latest

  post_build:
    commands:
      - echo Pushing Docker images to ECR...
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$SOHAM_IMAGE:latest
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ZAID_IMAGE:latest

      - echo Writing imagedefinitions.json...
      - printf '[{"name":"%s","imageUri":"%s"},{"name":"%s","imageUri":"%s"}]' \
        $SOHAM_IMAGE $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$SOHAM_IMAGE:latest \
        $ZAID_IMAGE $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ZAID_IMAGE:latest \
        > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

