version: 0.2

phases:
  pre_build:
    commands:
      - echo "ðŸ” Logging in to Amazon ECR..."
      - export REGION=ap-south-1
      - export ACCOUNT_ID=948082844272
      - export ECR_URL=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      - echo "Using ECR: $ECR_URL"
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_URL

  build:
    commands:
      - echo "ðŸ³ Building Docker images..."
      - docker build -t soham-app-app ./soham-app
      - docker build -t zaid-app-app ./zaid-app
      - echo "ðŸ”– Tagging Docker images..."
      - docker tag soham-app-app:latest $ECR_URL/soham-app-app:latest
      - docker tag zaid-app-app:latest $ECR_URL/zaid-app-app:latest

  post_build:
    commands:
      - echo "ðŸš€ Pushing Docker images to ECR..."
      - docker push $ECR_URL/soham-app-app:latest
      - docker push $ECR_URL/zaid-app-app:latest
      - echo "ðŸ“ Writing imagedefinitions.json for ECS CodeDeploy..."
      - printf '[{"name":"soham-app-app","imageUri":"%s"},{"name":"zaid-app-app","imageUri":"%s"}]' $ECR_URL/soham-app-app:latest $ECR_URL/zaid-app-app:latest > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

