version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 948082844272.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo "Building Docker images..."
      - docker build -t soham-app ./soham-app
      - docker build -t zaid-app ./zaid-app
      - docker tag soham-app:latest 948082844272.dkr.ecr.ap-south-1.amazonaws.com/soham-app:latest
      - docker tag zaid-app:latest 948082844272.dkr.ecr.ap-south-1.amazonaws.com/zaid-app:latest

  post_build:
    commands:
      - echo "Pushing Docker images to ECR..."
      - docker push 948082844272.dkr.ecr.ap-south-1.amazonaws.com/soham-app:latest
      - docker push 948082844272.dkr.ecr.ap-south-1.amazonaws.com/zaid-app:latest
      - echo "Creating imagedefinitions.json..."
      - printf '[{"name":"soham-app","imageUri":"948082844272.dkr.ecr.ap-south-1.amazonaws.com/soham-app:latest"},{"name":"zaid-app","imageUri":"948082844272.dkr.ecr.ap-south-1.amazonaws.com/zaid-app:latest"}]' > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

